safe:        false
auto:        true
pygments:    false
#markdown:    rdiscount
permalink:   none
title:       Google App Engine Design Patterns
exclude:     [".git", ".gitignore"]

author:
  name: najeira
