safe:        false
auto:        true
baseurl:     /gae_design_pattern/
pygments:    true
#markdown:    rdiscount
permalink:   none
title:       Google App Engine Design Patterns
exclude:     [".git", ".gitignore"]

author:
  name: najeira
